name: Publish to NPM

on:
  push:
    branches:
      - master # Adjust if you use a different default branch
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14
          registry-url: "https://registry.npmjs.org/"

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Publish to NPM
        run: npm publish --access public
